locales:
  available: ["en", "vi"]
  default: "en"
microposts:
  content:
    length: 140
  image:
    accept: "image/jpeg,image/gif,image/png"
  paginate:
    per_page: 10
  picture_size: 5
sessions:
  remember_me: "1"
static_pages:
  feed:
    paginate:
      per_page: 4
users:
  email:
    max_length: 255
  followers:
    paginate:
      per_page: 10
  following:
    paginate:
      per_page: 10
  gravatar:
    size: 50
    small_size: 30
  name:
    max_length: 50
  paginate:
    per_page: 10
  password:
    min_length: 6
    reset_expired: 2
